name: streamlit-app-env  # You can choose any name for your environment
channels:
  - defaults
dependencies:
  - python=3.11.4  # Specify the Python version you want to use
  - streamlit   # Install Streamlit
  - pip
# Add other dependencies as needed
pip:
  - langchain